name: tft_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=1.13.1
  - cudatoolkit=11.6
  - pytorch-forecasting=0.10.2
  - pytorch-lightning=1.9.0
  - numpy=1.24.2
  - pandas=1.5.3
  - scikit-learn=1.0.2
  - scipy=1.10.1
  - matplotlib-base=3.7.0
  - tqdm=4.64.1
  - pip:
    - torch==1.13.1+cu116
    - hydroeval==0.1.0
    - typing-extensions==4.5.0
